### ISSUE TITLE
Fatal Error -Line 33

### ISSUE THREAD

**Issue by ryangdar** [EnhancedAthlete/EA-WP-AWS-SNS-Client-REST-Endpoint#1]
Getting a fatal error when attempting to activate this plugin: "Fatal error: require_once(): Failed opening required './autoload.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear')"
For the path I used: 
require_once plugin_dir_path(‘home/my_username/public_html/wp-content/plugins/amazon-web-services/vendor/aws/aws-autoloader.php’) . 'autoload.php'; I have installed the AWS SDK for PHPplugin for Wordpress.

**Comment by BrianHenryIE** [comment]
This plugin has no dependency on the AWS SDK – this is basically just a REST endpoint with a admin notification for confirming subscription requests.

The first thing that might be problem is: did you download the zip from the release or did you just upload the code? – it needs `composer install` run first.

I'll send you my ph# on LinkedIn now.

**Comment by ryangdar** [comment]
Thanks! Issue closed
